/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminMfaChallengeRouteImport } from './routes/admin-mfa-challenge'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProvaRouteImport } from './routes/prova'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminAdministratorsRouteImport } from './routes/_admin/admin.administrators'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin/admin.analytics'
import { Route as AdminAdminAuditLogsRouteImport } from './routes/_admin/admin.audit-logs'
import { Route as AdminAdminFeaturesRouteImport } from './routes/_admin/admin.features'
import { Route as AdminAdminPaymentsRouteImport } from './routes/_admin/admin.payments'
import { Route as AdminAdminPlansRouteImport } from './routes/_admin/admin.plans'
import { Route as AdminAdminSecurityRouteImport } from './routes/_admin/admin.security'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminSubscriptionsRouteImport } from './routes/_admin/admin.subscriptions'
import { Route as AdminAdminSystemRouteImport } from './routes/_admin/admin.system'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardSubscriptionRouteImport } from './routes/_authenticated/dashboard.subscription'
import { Route as AuthenticatedDashboardTool1RouteImport } from './routes/_authenticated/dashboard.tool-1'
import { Route as AuthenticatedDashboardTool2RouteImport } from './routes/_authenticated/dashboard.tool-2'
import { Route as AuthenticatedDashboardTool3RouteImport } from './routes/_authenticated/dashboard.tool-3'
import { Route as AuthenticatedDashboardTool4RouteImport } from './routes/_authenticated/dashboard.tool-4'
import { Route as AuthenticatedDashboardTool5RouteImport } from './routes/_authenticated/dashboard.tool-5'
import { Route as AuthenticatedDashboardTool6RouteImport } from './routes/_authenticated/dashboard.tool-6'
import { Route as AuthenticatedDashboardTool7RouteImport } from './routes/_authenticated/dashboard.tool-7'
import { Route as AuthenticatedDashboardTool8RouteImport } from './routes/_authenticated/dashboard.tool-8'
import { Route as AuthenticatedDashboardUsageRouteImport } from './routes/_authenticated/dashboard.usage'
import { Route as AdminAdminUsersIdRouteImport } from './routes/_admin/admin.users.$id'
import { Route as ApiPublicLemonSqueezyWebhookRouteImport } from './routes/api/public/lemon-squeezy.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMfaChallengeRoute = AdminMfaChallengeRouteImport.update({
  id: '/admin-mfa-challenge',
  path: '/admin-mfa-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvaRoute = ProvaRouteImport.update({
  id: '/prova',
  path: '/prova',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAdministratorsRoute =
  AdminAdminAdministratorsRouteImport.update({
    id: '/administrators',
    path: '/administrators',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditLogsRoute = AdminAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFeaturesRoute = AdminAdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPlansRoute = AdminAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSecurityRoute = AdminAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSubscriptionsRoute = AdminAdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSystemRoute = AdminAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSubscriptionRoute =
  AuthenticatedDashboardSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTool1Route =
  AuthenticatedDashboardTool1RouteImport.update({
    id: '/tool-1',
    path: '/tool-1',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTool2Route =
  AuthenticatedDashboardTool2RouteImport.update({
    id: '/tool-2',
    path: '/tool-2',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTool3Route =
  AuthenticatedDashboardTool3RouteImport.update({
    id: '/tool-3',
    path: '/tool-3',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTool4Route =
  AuthenticatedDashboardTool4RouteImport.update({
    id: '/tool-4',
    path: '/tool-4',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTool5Route =
  AuthenticatedDashboardTool5RouteImport.update({
    id: '/tool-5',
    path: '/tool-5',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTool6Route =
  AuthenticatedDashboardTool6RouteImport.update({
    id: '/tool-6',
    path: '/tool-6',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTool7Route =
  AuthenticatedDashboardTool7RouteImport.update({
    id: '/tool-7',
    path: '/tool-7',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTool8Route =
  AuthenticatedDashboardTool8RouteImport.update({
    id: '/tool-8',
    path: '/tool-8',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsageRoute =
  AuthenticatedDashboardUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminAdminUsersIdRoute = AdminAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminUsersRoute,
} as any)
const ApiPublicLemonSqueezyWebhookRoute =
  ApiPublicLemonSqueezyWebhookRouteImport.update({
    id: '/api/public/lemon-squeezy/webhook',
    path: '/api/public/lemon-squeezy/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-mfa-challenge': typeof AdminMfaChallengeRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/prova': typeof ProvaRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/administrators': typeof AdminAdminAdministratorsRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/features': typeof AdminAdminFeaturesRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/plans': typeof AdminAdminPlansRoute
  '/admin/security': typeof AdminAdminSecurityRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/admin/system': typeof AdminAdminSystemRoute
  '/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/subscription': typeof AuthenticatedDashboardSubscriptionRoute
  '/dashboard/tool-1': typeof AuthenticatedDashboardTool1Route
  '/dashboard/tool-2': typeof AuthenticatedDashboardTool2Route
  '/dashboard/tool-3': typeof AuthenticatedDashboardTool3Route
  '/dashboard/tool-4': typeof AuthenticatedDashboardTool4Route
  '/dashboard/tool-5': typeof AuthenticatedDashboardTool5Route
  '/dashboard/tool-6': typeof AuthenticatedDashboardTool6Route
  '/dashboard/tool-7': typeof AuthenticatedDashboardTool7Route
  '/dashboard/tool-8': typeof AuthenticatedDashboardTool8Route
  '/dashboard/usage': typeof AuthenticatedDashboardUsageRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/users/$id': typeof AdminAdminUsersIdRoute
  '/api/public/lemon-squeezy/webhook': typeof ApiPublicLemonSqueezyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-mfa-challenge': typeof AdminMfaChallengeRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/prova': typeof ProvaRoute
  '/terms': typeof TermsRoute
  '/admin/administrators': typeof AdminAdminAdministratorsRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/features': typeof AdminAdminFeaturesRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/plans': typeof AdminAdminPlansRoute
  '/admin/security': typeof AdminAdminSecurityRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/admin/system': typeof AdminAdminSystemRoute
  '/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/subscription': typeof AuthenticatedDashboardSubscriptionRoute
  '/dashboard/tool-1': typeof AuthenticatedDashboardTool1Route
  '/dashboard/tool-2': typeof AuthenticatedDashboardTool2Route
  '/dashboard/tool-3': typeof AuthenticatedDashboardTool3Route
  '/dashboard/tool-4': typeof AuthenticatedDashboardTool4Route
  '/dashboard/tool-5': typeof AuthenticatedDashboardTool5Route
  '/dashboard/tool-6': typeof AuthenticatedDashboardTool6Route
  '/dashboard/tool-7': typeof AuthenticatedDashboardTool7Route
  '/dashboard/tool-8': typeof AuthenticatedDashboardTool8Route
  '/dashboard/usage': typeof AuthenticatedDashboardUsageRoute
  '/admin': typeof AdminAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/users/$id': typeof AdminAdminUsersIdRoute
  '/api/public/lemon-squeezy/webhook': typeof ApiPublicLemonSqueezyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-mfa-challenge': typeof AdminMfaChallengeRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/prova': typeof ProvaRoute
  '/terms': typeof TermsRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_admin/admin/administrators': typeof AdminAdminAdministratorsRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/_admin/admin/features': typeof AdminAdminFeaturesRoute
  '/_admin/admin/payments': typeof AdminAdminPaymentsRoute
  '/_admin/admin/plans': typeof AdminAdminPlansRoute
  '/_admin/admin/security': typeof AdminAdminSecurityRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/_admin/admin/system': typeof AdminAdminSystemRoute
  '/_admin/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/subscription': typeof AuthenticatedDashboardSubscriptionRoute
  '/_authenticated/dashboard/tool-1': typeof AuthenticatedDashboardTool1Route
  '/_authenticated/dashboard/tool-2': typeof AuthenticatedDashboardTool2Route
  '/_authenticated/dashboard/tool-3': typeof AuthenticatedDashboardTool3Route
  '/_authenticated/dashboard/tool-4': typeof AuthenticatedDashboardTool4Route
  '/_authenticated/dashboard/tool-5': typeof AuthenticatedDashboardTool5Route
  '/_authenticated/dashboard/tool-6': typeof AuthenticatedDashboardTool6Route
  '/_authenticated/dashboard/tool-7': typeof AuthenticatedDashboardTool7Route
  '/_authenticated/dashboard/tool-8': typeof AuthenticatedDashboardTool8Route
  '/_authenticated/dashboard/usage': typeof AuthenticatedDashboardUsageRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_admin/admin/users/$id': typeof AdminAdminUsersIdRoute
  '/api/public/lemon-squeezy/webhook': typeof ApiPublicLemonSqueezyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-mfa-challenge'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/prova'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/admin/administrators'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/features'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/users'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/dashboard/tool-1'
    | '/dashboard/tool-2'
    | '/dashboard/tool-3'
    | '/dashboard/tool-4'
    | '/dashboard/tool-5'
    | '/dashboard/tool-6'
    | '/dashboard/tool-7'
    | '/dashboard/tool-8'
    | '/dashboard/usage'
    | '/admin/'
    | '/dashboard/'
    | '/admin/users/$id'
    | '/api/public/lemon-squeezy/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-mfa-challenge'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/prova'
    | '/terms'
    | '/admin/administrators'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/features'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/users'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/dashboard/tool-1'
    | '/dashboard/tool-2'
    | '/dashboard/tool-3'
    | '/dashboard/tool-4'
    | '/dashboard/tool-5'
    | '/dashboard/tool-6'
    | '/dashboard/tool-7'
    | '/dashboard/tool-8'
    | '/dashboard/usage'
    | '/admin'
    | '/dashboard'
    | '/admin/users/$id'
    | '/api/public/lemon-squeezy/webhook'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/admin-mfa-challenge'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/prova'
    | '/terms'
    | '/_admin/admin'
    | '/_authenticated/dashboard'
    | '/_admin/admin/administrators'
    | '/_admin/admin/analytics'
    | '/_admin/admin/audit-logs'
    | '/_admin/admin/features'
    | '/_admin/admin/payments'
    | '/_admin/admin/plans'
    | '/_admin/admin/security'
    | '/_admin/admin/settings'
    | '/_admin/admin/subscriptions'
    | '/_admin/admin/system'
    | '/_admin/admin/users'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/subscription'
    | '/_authenticated/dashboard/tool-1'
    | '/_authenticated/dashboard/tool-2'
    | '/_authenticated/dashboard/tool-3'
    | '/_authenticated/dashboard/tool-4'
    | '/_authenticated/dashboard/tool-5'
    | '/_authenticated/dashboard/tool-6'
    | '/_authenticated/dashboard/tool-7'
    | '/_authenticated/dashboard/tool-8'
    | '/_authenticated/dashboard/usage'
    | '/_admin/admin/'
    | '/_authenticated/dashboard/'
    | '/_admin/admin/users/$id'
    | '/api/public/lemon-squeezy/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminMfaChallengeRoute: typeof AdminMfaChallengeRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProvaRoute: typeof ProvaRoute
  TermsRoute: typeof TermsRoute
  ApiPublicLemonSqueezyWebhookRoute: typeof ApiPublicLemonSqueezyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mfa-challenge': {
      id: '/admin-mfa-challenge'
      path: '/admin-mfa-challenge'
      fullPath: '/admin-mfa-challenge'
      preLoaderRoute: typeof AdminMfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prova': {
      id: '/prova'
      path: '/prova'
      fullPath: '/prova'
      preLoaderRoute: typeof ProvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/administrators': {
      id: '/_admin/admin/administrators'
      path: '/administrators'
      fullPath: '/admin/administrators'
      preLoaderRoute: typeof AdminAdminAdministratorsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/audit-logs': {
      id: '/_admin/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAdminAuditLogsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/features': {
      id: '/_admin/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminAdminFeaturesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/payments': {
      id: '/_admin/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/plans': {
      id: '/_admin/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminAdminPlansRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/security': {
      id: '/_admin/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminAdminSecurityRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/subscriptions': {
      id: '/_admin/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminAdminSubscriptionsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/system': {
      id: '/_admin/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminAdminSystemRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/subscription': {
      id: '/_authenticated/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof AuthenticatedDashboardSubscriptionRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tool-1': {
      id: '/_authenticated/dashboard/tool-1'
      path: '/tool-1'
      fullPath: '/dashboard/tool-1'
      preLoaderRoute: typeof AuthenticatedDashboardTool1RouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tool-2': {
      id: '/_authenticated/dashboard/tool-2'
      path: '/tool-2'
      fullPath: '/dashboard/tool-2'
      preLoaderRoute: typeof AuthenticatedDashboardTool2RouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tool-3': {
      id: '/_authenticated/dashboard/tool-3'
      path: '/tool-3'
      fullPath: '/dashboard/tool-3'
      preLoaderRoute: typeof AuthenticatedDashboardTool3RouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tool-4': {
      id: '/_authenticated/dashboard/tool-4'
      path: '/tool-4'
      fullPath: '/dashboard/tool-4'
      preLoaderRoute: typeof AuthenticatedDashboardTool4RouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tool-5': {
      id: '/_authenticated/dashboard/tool-5'
      path: '/tool-5'
      fullPath: '/dashboard/tool-5'
      preLoaderRoute: typeof AuthenticatedDashboardTool5RouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tool-6': {
      id: '/_authenticated/dashboard/tool-6'
      path: '/tool-6'
      fullPath: '/dashboard/tool-6'
      preLoaderRoute: typeof AuthenticatedDashboardTool6RouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tool-7': {
      id: '/_authenticated/dashboard/tool-7'
      path: '/tool-7'
      fullPath: '/dashboard/tool-7'
      preLoaderRoute: typeof AuthenticatedDashboardTool7RouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tool-8': {
      id: '/_authenticated/dashboard/tool-8'
      path: '/tool-8'
      fullPath: '/dashboard/tool-8'
      preLoaderRoute: typeof AuthenticatedDashboardTool8RouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/usage': {
      id: '/_authenticated/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof AuthenticatedDashboardUsageRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/admin/users/$id': {
      id: '/_admin/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminAdminUsersIdRouteImport
      parentRoute: typeof AdminAdminUsersRoute
    }
    '/api/public/lemon-squeezy/webhook': {
      id: '/api/public/lemon-squeezy/webhook'
      path: '/api/public/lemon-squeezy/webhook'
      fullPath: '/api/public/lemon-squeezy/webhook'
      preLoaderRoute: typeof ApiPublicLemonSqueezyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAdminUsersRouteChildren {
  AdminAdminUsersIdRoute: typeof AdminAdminUsersIdRoute
}

const AdminAdminUsersRouteChildren: AdminAdminUsersRouteChildren = {
  AdminAdminUsersIdRoute: AdminAdminUsersIdRoute,
}

const AdminAdminUsersRouteWithChildren = AdminAdminUsersRoute._addFileChildren(
  AdminAdminUsersRouteChildren,
)

interface AdminAdminRouteChildren {
  AdminAdminAdministratorsRoute: typeof AdminAdminAdministratorsRoute
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminAuditLogsRoute: typeof AdminAdminAuditLogsRoute
  AdminAdminFeaturesRoute: typeof AdminAdminFeaturesRoute
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminPlansRoute: typeof AdminAdminPlansRoute
  AdminAdminSecurityRoute: typeof AdminAdminSecurityRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminSubscriptionsRoute: typeof AdminAdminSubscriptionsRoute
  AdminAdminSystemRoute: typeof AdminAdminSystemRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRouteWithChildren
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAdministratorsRoute: AdminAdminAdministratorsRoute,
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminAuditLogsRoute: AdminAdminAuditLogsRoute,
  AdminAdminFeaturesRoute: AdminAdminFeaturesRoute,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminPlansRoute: AdminAdminPlansRoute,
  AdminAdminSecurityRoute: AdminAdminSecurityRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminSubscriptionsRoute: AdminAdminSubscriptionsRoute,
  AdminAdminSystemRoute: AdminAdminSystemRoute,
  AdminAdminUsersRoute: AdminAdminUsersRouteWithChildren,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSubscriptionRoute: typeof AuthenticatedDashboardSubscriptionRoute
  AuthenticatedDashboardTool1Route: typeof AuthenticatedDashboardTool1Route
  AuthenticatedDashboardTool2Route: typeof AuthenticatedDashboardTool2Route
  AuthenticatedDashboardTool3Route: typeof AuthenticatedDashboardTool3Route
  AuthenticatedDashboardTool4Route: typeof AuthenticatedDashboardTool4Route
  AuthenticatedDashboardTool5Route: typeof AuthenticatedDashboardTool5Route
  AuthenticatedDashboardTool6Route: typeof AuthenticatedDashboardTool6Route
  AuthenticatedDashboardTool7Route: typeof AuthenticatedDashboardTool7Route
  AuthenticatedDashboardTool8Route: typeof AuthenticatedDashboardTool8Route
  AuthenticatedDashboardUsageRoute: typeof AuthenticatedDashboardUsageRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSubscriptionRoute:
      AuthenticatedDashboardSubscriptionRoute,
    AuthenticatedDashboardTool1Route: AuthenticatedDashboardTool1Route,
    AuthenticatedDashboardTool2Route: AuthenticatedDashboardTool2Route,
    AuthenticatedDashboardTool3Route: AuthenticatedDashboardTool3Route,
    AuthenticatedDashboardTool4Route: AuthenticatedDashboardTool4Route,
    AuthenticatedDashboardTool5Route: AuthenticatedDashboardTool5Route,
    AuthenticatedDashboardTool6Route: AuthenticatedDashboardTool6Route,
    AuthenticatedDashboardTool7Route: AuthenticatedDashboardTool7Route,
    AuthenticatedDashboardTool8Route: AuthenticatedDashboardTool8Route,
    AuthenticatedDashboardUsageRoute: AuthenticatedDashboardUsageRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminMfaChallengeRoute: AdminMfaChallengeRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProvaRoute: ProvaRoute,
  TermsRoute: TermsRoute,
  ApiPublicLemonSqueezyWebhookRoute: ApiPublicLemonSqueezyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
